@startuml Services

class ImageCapture::Result { 
    + error_log: [] String;
    + status: { "OK", "ERROR", "NOT_FOUND" };
    + image: ? Photo;
    + http_status: Integer;
    + items_ok: [] String;
    + items_pending: [] String;  
} 

class ImageCaptureService <<Singleton>> {
    + capture(url: String): ImageCapture::Result;
    + capture_many(url_list: [] String): ImageCapture::Result;
    + capture_from_flow(entries: [] ExternalEntry);
}

class ImageImportService <<Singleton>> {
    + import(fname: String): ImageCapture::Result;
    + import_directory(dirname: String): ImageCapture::Result;
}

interface SourceFlowService {
    + set_source_api(api_record: SourceAPI);
    + set_flow_params(flow_params: {});
    + get_entries(since: ? DateTime): [] ExternalEntry;  
}

TumblrSourceService --|> SourceFlowService
class TumblrSourceService {

} 

@enduml

